---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pleo-stack

commonLabels:
  app.kubernetes.io/managed-by: kustomize

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: app-tinjis-cm
    envs:
      - env
