---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sinatra-money-adapter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-sinatra-money-adapter
rules:
- apiGroups:
  - ""
  resources:
  - ""
  verbs:
  - ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-sinatra-money-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-sinatra-money-adapter
subjects:
- kind: ServiceAccount
  name: app-sinatra-money-adapter