---
apiVersion: v1
kind: Service
metadata:
  name: app-sinatra-money-adapter-svc
  labels:
    app.kubernetes.io/name: app-sinatra-money-adapter-svc
    app.kubernetes.io/part-of: PleoStack
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app.kubernetes.io/name: app-sinatra-money-adapter
    app.kubernetes.io/part-of: PleoStack
